### ISSUE TITLE
Current state of project

### ISSUE THREAD

**Issue by soxrok2212** [Rohde-Schwarz/dlepard#1]
Hi! First, I'd like to say thanks for making this project public! 

I'm attempting to test the code and I see some TODO comments. Particularly in the enter_session_initialisation_state, I'm a bit confused as to why the message is being created from UDPProxy and not TCPProxy. Is the TCPProxy incomplete? I've worked around a bit and managed to send the session initialization packet as a tcp frame but with no payload.

Thank you!

**Comment by lawa23** [comment]
Hey, thank you for reaching out!

I have good news: **The project is still alive!**
I am currently working on this and related projects full-time again.

Unfortunately, I haven't pushed to this repo since I took over the project in 2019. Sorry about that!
I will publish all my work up to **Release 1.0.0** today. **In this version, TCP should be working as expected.**

Additionally, work on version 2.0.0 is well under way.
It will include some major restructuring, proper packaging, and more documentation.
I will lay out the roadmap in the README and trough a few new issues.

Cheers,
Lars

**Comment by soxrok2212** [comment]
Cheers to that! Thanks for the speedy response! I’ll check it out 👍
